[package]
authors = ["Shannon Skipper"]
categories = ["command-line-utilities", "text-processing"]
description = "Output a tally of the number of times unique words appear in source input."
edition = "2024"
homepage = "https://github.com/havenwood/word-tally"
keywords = ["cli", "tally", "words", "count"]
license = "MIT"
name = "word-tally"
repository = "https://github.com/havenwood/word-tally"
version = "0.24.0"

[dependencies]
anyhow = "1.0.83"
clap = { version = "4.5.4", features = ["derive"] }
csv = "1.3.1"
memchr = "2.7.4"
memmap2 = "0.9.5"
rayon = "1.10.0"
regex = "1.11.1"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.85"
unescaper = "0.1.4"
unicode-segmentation = "1.11.0"

[features]
default = []

[dev-dependencies]
assert_cmd = "2.0.14"
criterion = "0.6.0"
fake = "4.2.0"
predicates = "3.1.0"
tempfile = "3.10.1"

[[bench]]
name = "core"
harness = false

[[bench]]
name = "features"
harness = false

[[bench]]
name = "io"
harness = false

[[bench]]
name = "multi_file"
harness = false

[profile.release]
lto = true
strip = true

[lints.clippy]
cargo = "deny"
correctness = "deny"
nursery = "deny"
pedantic = "warn"
perf = "deny"
suspicious = "deny"

[lints.rust]
future_incompatible = "deny"
let_underscore = "deny"
missing_debug_implementations = "deny"
nonstandard_style = "deny"
rust_2018_compatibility = "deny"
rust_2018_idioms = "deny"
rust_2021_compatibility = "deny"
rust_2024_compatibility = "deny"
unused = "deny"
