[package]
authors = ["Shannon Skipper"]
categories = ["command-line-utilities", "text-processing"]
description = "Output a tally of the number of times unique words appear in source input."
edition = "2021"
homepage = "https://github.com/havenwood/word-tally"
keywords = ["cli", "tally", "words", "count"]
license = "MIT"
name = "word-tally"
repository = "https://github.com/havenwood/word-tally"
version = "0.5.0"

[dependencies]
anyhow = "1.0.83"
clap = { version = "4.5.4", features = ["derive"] }
clap-stdin = "0.4.0"
unescaper = "0.1.4"
unicode-segmentation = "1.11.0"

[dev-dependencies]
assert_cmd = "2.0.14"
criterion = "0.5.1"
once_cell = "1.19.0"
predicates = "3.1.0"

[[bench]]
name = "bench"
harness = false

[profile.release]
lto = true
strip = true

[lints.clippy]
cargo = "warn"
nursery = "warn"

[lints.rust]
future_incompatible = "warn"
let_underscore = "warn"
nonstandard_style = "warn"
rust_2018_compatibility = "warn"
rust_2018_idioms = "warn"
rust_2021_compatibility = "warn"
rust_2024_compatibility = "warn"
unused = "warn"
