[package]
name = "word-tally"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
unicode-segmentation = "1.11.0"

[profile.release]
codegen-units = 1
incremental = true
lto = true
opt-level = "s"
panic = "abort"
strip = true
