cargo-features = ["edition2024"]

[package]
authors = ["Shannon Skipper"]
categories = ["command-line-utilities", "text-processing"]
description = "Output a tally of the number of times unique words appear in source input."
edition = "2024"
exclude = ["/tests"]
homepage = "https://github.com/havenwood/word-tally"
keywords = ["cli", "tally", "words", "count"]
license = "MIT"
name = "word-tally"
repository = "https://github.com/havenwood/word-tally"
version = "0.1.0"

[dependencies]
anyhow = "1.0.83"
clap = { version = "4.5.4", features = ["derive"] }
clap-stdin = "0.4.0"
unescaper = "0.1.4"
unicode-segmentation = "1.11.0"

[profile.release]
codegen-units = 1
incremental = true
lto = true
opt-level = "s"
panic = "abort"
strip = true
